[package]
name = "simple_generators_adapter"
version = "0.2.0"
authors = ["Vova <vova616@gmail.com>"]
edition = "2021"
description = "helper crate for simple_generators, containing the adapter"
license = "MIT"

[dependencies]
